apiVersion: "v1"
kind: "Service"
metadata:
  name: "link-app"
  labels:
    app: "link-app"
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30000
  selector:
    app: "link-app"
  type: NodePort
